version: '3'

services:
  minecraft:
    build:
      context: minecraft/
      dockerfile: ../Dockerfile
    image: minecraft_local_server
    container_name: minecraft
    env_file:
      - ./.envs/.minecraft/.jvm
    volumes:
      - ./minecraft/server.properties:/minecraft/server.properties
#      - ./minecraft/banned-ips.json:/minecraft/banned-ips.json
#      - ./minecraft/banned-players.json:/minecraft/banned-players.json
#      - ./minecraft/ops.json:/minecraft/ops.json
#      - ./minecraft/options.txt:/minecraft/options.txt
#      - ./minecraft/whitelist.json:/minecraft/whitelist.json
#      - ./minecraft/logs:/minecraft/logs:z
    ports:
      - "25565:25565"
    command: ./start