version: '3'

services:
  minecraft:
    build:
      context: .
      dockerfile: ./compose/minecraft/Dockerfile
    image: minecraft_local_server
    restart: unless-stopped
    container_name: minecraft
    env_file:
      - ./.envs/.minecraft/.jvm
    volumes:
      - ./minecraft:/minecraft:z
    ports:
      - "25565:25565"
    command: /start