version: '3'

services:
  minecraft:
    build:
      context: .
      dockerfile: ./compose/minecraft/Dockerfile
    image: minecraft_local_server
    restart: unless-stopped
    container_name: minecraft
    environment:
      JAVA_CMD: java
      JAVA_PARAMETERS: >
        -Dfml.queryResult=confirm -XX:+UseG1GC -XX:+UnlockExperimentalVMOptions
        -Xmx6144M -Xms4096M -XX:+UseConcMarkSweepGC -XX:+UseParNewGC
        -XX:+CMSIncrementalPacing -XX:+CMSClassUnloadingEnabled
        -XX:ParallelGCThreads=5 -XX:+AggressiveOpts
        -XX:MinHeapFreeRatio=5 -XX:MaxHeapFreeRatio=10
      JAR_FILENAME: forge-1.12.2-14.23.5.2846-universal.jar
    volumes:
      - ./minecraft:/minecraft:z
    ports:
      - "25565:25565"
    command: /start