#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

# server function
start_server() {
  cd $WORKING_DIR
  java -server $JAVA_OPTS -jar $JAR_FILENAME nogui
}

echo "Starting server"
start_server