#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

# server function
start_server() {
    "$JAVA_CMD" -server ${JAVA_PARAMETERS} -jar FTBserver-1.12.2-14.23.5.2846-universal.jar nogui
}

echo "Starting server"
rm -f autostart.stamp
start_server