#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

# server function
start_server() {
    "$JAVA_CMD" -server ${JAVA_PARAMETERS} -jar ${JAR_FILENAME} nogui
}

echo "Starting server"
start_server