#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

# Fix work directory
# Some GUIs set wrong working directory which breaks relative paths
cd -- "$(dirname "$0")"

# check eula.txt
eula_false() {
    grep -q 'eula=false' eula.txt
    return $?
}

# if eula.txt has not been signed, inform user
if [ -f eula.txt ] && eula_false ; then
    echo "EULA has not been signed. Startup has been exited."
    read ignored
    exit
fi

# if eula.txt is missing inform user
if [ ! -f eula.txt ]; then
    echo "Missing eula.txt. Startup has been exited."
    read ignored
fi

echo "All tests were completed successfully... continuing build..."